### ISSUE TITLE
validateInput

### ISSUE THREAD

**Issue by bwitzen** [jlnjnsn/Ghost#4]
Zeker in Swift zijn er betere oplossingen beschikbaar dan de string 'error' retourneren. Bovendien vind ik het vreemd dat een functie genaamd "validate" geen bool retourneert.

    func validateInput(input: String) -> String {
        let firstLetter: Character = Array(input)[0]
        let output = String(firstLetter).lowercaseString
        let range = output.rangeOfCharacterFromSet(lowercaseCharacterSet)
        
        if range == nil {
            return "error"
        } else {
            return output
        }
    }

**Comment by jlnjnsn** [comment]
methods gecombineerd
